repos:
  - repo: local
    hooks:
      - id: pytest-check
        stages: [push]
        types: [python]
        name: pytest-check
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        stages: [commit]
        language_version: python3.11
